apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: equipocredito
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: rodrigotobarhites/equipocredito-escalab:frontend
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: frontend-config
        volumeMounts:
        - name: frontend-config-volume
          mountPath: /template.html
          subPath: template.html
      volumes:
      - name: frontend-config-volume
        configMap:
          name: frontend-config
