apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: equipocredito
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: rodrigotobarhites/equipocredito-escalab:backend
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: backend-config
        env:
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: DB_HOST
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: DB_PASSWORD
        volumeMounts:
        - name: backend-config-volume
          mountPath: /datos.json
          subPath: datos.json
      volumes:
      - name: backend-config-volume
        configMap:
          name: backend-config
